config/routes.rb
Producer::Application.routes.draw do

  namespace :post do
    resources :categories
  end

  resources :posts do
    resources :comments
  end

  root to: 'pages#index'
  get "pages/index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :excerpt, :title, :author_id

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :categories, :class_name => 'Post::Category'

  validates :title, :body, :author, presence: true
  validates_associated :author

end

app/models/post/category.rb
class Post::Category < ActiveRecord::Base
  RAILS      = 1
  RUBY       = 2
  JAVASCRIPT = 3
  HTML       = 4
  CSS        = 5

  attr_accessible :name
  has_and_belongs_to_many :posts

  def name
    read_attribute(:name).upcase
  end

  def name=(value)
    write_attribute(:name, value.upcase)
  end
end

app/controllers/post/categories_controller.rb
class Post::CategoriesController < ApplicationController
  # GET /post/categories
  # GET /post/categories.json
  def index
    @post_categories = Post::Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @post_categories }
    end
  end

  # GET /post/categories/1
  # GET /post/categories/1.json
  def show
    @post_category = Post::Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post_category }
    end
  end

  # GET /post/categories/new
  # GET /post/categories/new.json
  def new
    @post_category = Post::Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post_category }
    end
  end

  # GET /post/categories/1/edit
  def edit
    @post_category = Post::Category.find(params[:id])
  end

  # POST /post/categories
  # POST /post/categories.json
  def create
    @post_category = Post::Category.new(params[:post_category])

    respond_to do |format|
      if @post_category.save
        format.html { redirect_to @post_category, notice: 'Category was successfully created.' }
        format.json { render json: @post_category, status: :created, location: @post_category }
      else
        format.html { render action: "new" }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /post/categories/1
  # PUT /post/categories/1.json
  def update
    @post_category = Post::Category.find(params[:id])

    respond_to do |format|
      if @post_category.update_attributes(params[:post_category])
        format.html { redirect_to @post_category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post/categories/1
  # DELETE /post/categories/1.json
  def destroy
    @post_category = Post::Category.find(params[:id])
    @post_category.destroy

    respond_to do |format|
      format.html { redirect_to post_categories_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :load_authors, only: [:new, :edit, :create, :update]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
  def load_authors
    @authors = User.all
  end
end

app/helpers/post/categories_helper.rb
module Post::CategoriesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/post/categories/_form.html.erb
<%= form_for(@post_category) do |f| %>
  <% if @post_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post_category.errors.count, "error") %> prohibited this post_category from being saved:</h2>

      <ul>
      <% @post_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post/categories/edit.html.erb
<h1>Editing post_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @post_category %> |
<%= link_to 'Back', post_categories_path %>

app/views/post/categories/index.html.erb
<h1>Listing post_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @post_categories.each do |post_category| %>
  <tr>
    <td><%= post_category.name %></td>
    <td><%= link_to 'Show', post_category %></td>
    <td><%= link_to 'Edit', edit_post_category_path(post_category) %></td>
    <td><%= link_to 'Destroy', post_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_post_category_path %>

app/views/post/categories/new.html.erb
<h1>New post_category</h1>

<%= render 'form' %>

<%= link_to 'Back', post_categories_path %>

app/views/post/categories/show.html.erb
<p>
  <b>Name:</b>
  <%= @post_category.name %>
</p>


<%= link_to 'Edit', edit_post_category_path(@post_category) %> |
<%= link_to 'Back', post_categories_path %>